# Generated by Django 3.1.7 on 2021-03-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
    ]
