# Generated by Django 3.1.7 on 2021-05-14 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210512_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 7, 27, 16, 178320, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='d47d89cdad4194a0064410ea75d750b3bca9b8080ddc7557cc37d58694b83ebd', max_length=64),
        ),
    ]
