# Generated by Django 3.1.7 on 2021-06-16 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210615_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 18, 18, 8, 419063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='d6e70d991b7d3c0188c1d96dfd2ff805980fb20111a9c52aec72b7416e135261', max_length=64),
        ),
    ]
