# Generated by Django 3.1.7 on 2021-06-18 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210616_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 15, 55, 549711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='30ddcfafb22c139e4eb12abd52d8d187f848eb818ff347176497d95429bdf11e', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_face', null=True, upload_to='profiles'),
        ),
    ]
