# Generated by Django 3.1.7 on 2021-03-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_answers_questions_reviews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
