# Generated by Django 3.1.7 on 2021-05-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210505_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.products'),
        ),
    ]
